keybinds:
  normal:
    - action: [GoToTab: 1,]
      key: [Alt: '1',]
    - action: [GoToTab: 2,]
      key: [Alt: '2',]
    - action: [GoToTab: 3,]
      key: [Alt: '3',]
    - action: [GoToTab: 4,]
      key: [Alt: '4',]
    - action: [GoToTab: 5,]
      key: [Alt: '5',]
    - action: [GoToTab: 6,]
      key: [Alt: '6',]
    - action: [GoToTab: 7,]
      key: [Alt: '7',]
    - action: [GoToTab: 8,]
      key: [Alt: '8',]
    - action: [GoToTab: 9,]
      key: [Alt: '9',]
    - action: [GoToTab: 0,]
      key: [Alt: '0',]

#themes:
# default:
#   fg: [0,0,0]
#   bg: [0,0,0]
#   black: [0,0,0]
#   red: [0,0,0]
#   green: [0,0,0]
#   yellow: [0,0,0]
#   blue: [0,0,0]
#   magenta: [0,0,0]
#   cyan: [0,0,0]
#   white: [0,0,0]
#   orange: [0,0,0]
#   gray: [0,0,0]

